name: 'Scripts runner'
description: 'An actions to bootsrap scripts that need to be run before pushing our code to an X env.'
author: 'nouailibh'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  scripts-folder:
    description: 'Your input description here'
    required: true

# Define your outputs here.
outputs:
  result:
    description: 'Either your scripts failed or successded.'

runs:
  using: node20
  main: dist/index.js
